### PR TITLE
HFP-2854: FitB reports updated to handle alternatives.

### PR DESCRIPTION
**Pull request by jwalits**
PR created to address: https://h5ptechnology.atlassian.net/browse/HFP-2854****
FitB Report updated to support "https://h5p.org/x-api/alternatives" extension

### CODE REVIEW

**Review by thomasmars — CHANGES_REQUESTED** [review]
I get a php error when running this:
` Notice: Trying to access array offset on value of type bool in /var/www/html/mod/hvp/reporting/type-processors/fill-in-processor.class.php on line `.
Also, this will not work for older versions of fill in the blanks, the reporting has to be backwards-compatible with older versions, so those reports can still be generated.
Finally, there are other content types that use this report processor, any content type that is a "fill-in" content type. These will no longer work with these changes, because they may not use he case-sensitivity or alternatives extensions.

**Comment by jwalits** [comment]
Thanks for the feedback @thomasmars,

I have updated the code to have it backwards compatible. In my testing so far, I haven't seen that PHP Notice you mentioned?

If you could please review and provide any feedback, it would be much appreciated.

Thanks,
Jay

**Review by thomasmars — CHANGES_REQUESTED** [review]
Looks much better.
The buildReportOutput function expects $caseMatters to be an array: https://github.com/h5p/h5p-php-report/blob/2a8f16223234c29fe324702b21d247a75dc5395e/type-processors/fill-in-processor.class.php#L56-L60 
This change makes the value a boolean, which causes the notice. You can enable Moodle debugging by following: https://docs.moodle.org/38/en/Debugging#Enabling_debugging

**Comment by jwalits** [comment]
Thanks @thomasmars,

I have made that change. Appreciate your feedback.

Regards,
Jay

**Comment by jwalits** [comment]
Hey @thomasmars,

Hope you are well. When you have a chance, would you be able to look at the updated patch?

Regards,
Jay

**Review by thomasmars — APPROVED** [review]
Looks good, we'll have to do some regression testing before merging it in. Thanks

**Comment by jwalits** [comment]
Hey @thomasmars,

Thanks for the update, looking forward to seeing this merged into main repo.

Regards,
Jay

**Comment by jwalits** [comment]
Hi @thomasmars,

Hope you are well? Do you have an ETA on when you think the changes will be merged into the main code?

Regards,
Jay

**Comment by jwalits** [comment]
Hi,

Any update on the regression testing with this one? Do you have an ETA when you expect the changes to be merged in?

Regards,
Jay

**Comment by thomasmars** [comment]
Sorry this is taking a while, we usually do pull requests and regression testing when we're about to release a new plugin version, but we've been swamped with building the content hub lately https://h5p.org/oer-hub-coming, so there's been no new releases. I have no ETA, but I'm pretty sure we'll be releasing a new version soon.

**Comment by golenkovm** [comment]
Hi @thomasmars 
Can you please let me know if this fix will be included into a new version?
And maybe now you know when it's going to be released (eg roughly in a week, in a month, in a year)?

Thanks,
Mikhail

**Comment by jarvil1** [comment]
Hello,

Any progress on this?

**Comment by jarvil1** [comment]
Hello,

When will this be available in mod_hvp? @thomasmars

**Comment by thomasmars** [comment]
With the next release.

**Comment by bozicm** [comment]
Hi, we'd try to fork with this patch but unfortunately we don't have any experience with H5P code. Is the code usable then as such? Or is this conflict a show stopper?

**Comment by golenkovm** [comment]
Hey @thomasmars 
The conflict is resolved now.
Could you please have a look and advise when this pull request might be merged in?

Cheers,
Mikhail

**Review by thomasmars — CHANGES_REQUESTED** [review]
Thanks, could you change the private static to constants instead, unless there is a specific reason for having them like this ?

**Comment by jwalits** [comment]
Hey @thomasmars 

Thanks for the feedbak. There was no specific reason for the static variables. I have updated the code to make them constants.

Regards,
Jwalit

**Review by thomasmars — APPROVED** [review]

**Comment by thomasmars** [comment]
Thanks :)

**Pull request merged**
