### PR TITLE
Support xAPI long-fill-in interactions

### PR DESCRIPTION
**Pull request by otacke**
The xAPI specification supports long-fill-in interactions that can be treated as fill-in exercises, but where the answer is usually longer that 250 characters, cmp. https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#interaction-types

This pull request adds support for long-fill-in interactions by relaying the answers to the fill-in processor.

### CODE REVIEW

**Comment by icc** [comment]
This seems fine to me. Although, there should probably be a different layout. Looking at the spec it seems fill-in is your typical html input, while the long-fill-in is more of a textarea.
Which content type are you using the for?

**Comment by otacke** [comment]
@icc I use it in Essay (have to check one thing in the other pull request for fill-in). This is just a minimum viable approach which is better than nothing. A different design might be useful, of course.

**Comment by otacke** [comment]
@icc I have now created a proposal for a long-fill-in processor. Compared to the fill-in processor, I merely used full width paragraphs instead of spans to reflect the long nature of the text. The design may need to be changed, but it's a start that can be used. If a correct responses pattern is given, it looks weird, but I assume it's pretty uncommon to have a long-fill-in with such a pattern anyway.

**Review by thomasmars — CHANGES_REQUESTED** [review]
It works nicely, good work! :) 
I think we should make the code more DRY though, could we re-use or extend the fill-in processor somehow to avoid all the duplicate code ?
A pull request must be added for Moodle as well to include the new LongFillInProcessor in the autoloader.php map.

**Comment by otacke** [comment]
@thomasmars Does PHP support overloading of functions when inheriting? I think it didn't, but I'll take a look. And I know about moodle ;-)

**Comment by thomasmars** [comment]
yes :) https://www.php.net/manual/en/language.oop5.inheritance.php

**Comment by otacke** [comment]
Easy-peasy then ...

**Comment by otacke** [comment]
@thomasmars 
Overloading was not as simple (or elegant at least) as I had hoped for. In fact, only the function _getPlaceholderReplacements_ has been modified, but I'd also have to keep _buildReportOutput_ and _generateHTML_ in the long-fill-in processor as the call traverses through these two. Works, but still a lot of code duplication.

I browsed the reporting code a little more and used the extras property to simply tell fill-in that it's a long-fill-in variant and it can set a modifier class on the container that the CSS can use to alter the stylesheet for long-fill-in interactions.

No duplicate code. No need to touch the moodle plugin. Can be cleanly merged with https://github.com/otacke/h5p-php-report/tree/fill-in-with-no-right-or-wrong to also support interactions without a CRP.

**Review by thomasmars — APPROVED** [review]

**Review by thomasmars — CHANGES_REQUESTED** [review]
I get the following error when trying to view a report for essay:
`PHP Warning: Invalid argument supplied for foreach() in /var/www/html/mod/hvp/reporting/type-processors/fill-in-processor.class.php on line 111`
It seems the report requires a correct responses pattern to be defined, but essay does not send it in.

**Comment by otacke** [comment]
@thomasmars The release version doesn't, the master version should.

**Comment by otacke** [comment]
@thomasmars And you should check https://github.com/h5p/h5p-php-report/pull/4 as for Essay there are no clear right/wrong answers, hence no correct responses pattern.

**Comment by thomasmars** [comment]
I see, so #4 should be merged in before this one ?

**Comment by otacke** [comment]
@thomasmars It was quite some time ago that I created this, but judging by my own pull-request message: yes :-)

> With these changes, if the xAPI statement does not contain a correct responses pattern for an xAPI fill-in interaction, it will display the response without marking the fields that were filled in in any way. It will also suppress the footer with the explanations for markings.

**Comment by icc** [comment]
But are we already storing reports from Essay? As long as we don't get any old reports outputting the warning.

**Comment by icc** [comment]
_Sorry, I tabbed to the wrong button..._

**Comment by thomasmars** [comment]
I see the current H5P.org version of Essay does not send the user response in the results, but the "master" branch version of Essay seem to have fixed this. So a new version of Essay has to be released in order for the reports to be displayed for Essay ?

I also see that with the new version of Essay the whole answer is wrapped within a "h5p-long-fill-in" container, I guess this would be okay if it breaks lines, now it just overflows the container and does not break into lines, also any linebreaks that the user has input is not registered and thus not reflected in the report. It does not look good:
essay_report

**Comment by otacke** [comment]
@thomasmars Yes, it's definitely necessary to release an update of Essay - that request has been pending since March 2018 anyway  https://h5ptechnology.atlassian.net/browse/HFP-1879 ;-) 

I'll look into the linebreak issue, but I can't promise to find the time before this weekend.

**Comment by otacke** [comment]
@thomasmars I just changed Essay to keep line breaks for reporting.

**Comment by thomasmars** [comment]
Created https://github.com/otacke/h5p-essay/pull/52 for keeping line breaks that is compatible with the changes merged in for https://github.com/h5p/h5p-php-report/commit/bf01e8bd0428dd8025b42afeeec593d220d62439

**Pull request merged**
